### ISSUE TITLE
Could not pass event PlayerInteractEvent to FactoryMod v1.4.0 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#110]
2015-06-25 20:38:31 [ERROR] Could not pass event PlayerInteractEvent to FactoryMod v1.4.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:604) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.Factorys.NetherFactory.getRepairs(NetherFactory.java:448) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.ABaseFactory.getAllInputs(ABaseFactory.java:250) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.ABaseFactory.checkHasMaterials(ABaseFactory.java:120) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.ABaseFactory.togglePower(ABaseFactory.java:167) ~[?:?]
        at com.github.igotyou.FactoryMod.listeners.FactoryModListener.playerInteractionEvent(FactoryModListener.java:241) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 18 more

**Comment by BlackXnt** [comment]
I found the problem. Pull will be up in a few mins.

**Comment by ProgrammerDan** [comment]
A+

**Comment by hlprimm** [comment]
I love you.

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/FactoryMod/pull/111

**Comment by ProgrammerDan** [comment]
Unless you're still seeing this @ttk2 probably safe to close. 

Looks like Thule repaired their factory a little bit ago, which confirms this fix worked.

**Comment by ttk2** [comment]
nice, closing.
