### ISSUE TITLE
During execution an NPE

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#169]
[14:39:18 INFO]: Bonkill issued server command: /fm                                                            [14/9247]
[14:39:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fm' in plugin FactoryMod v2.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.commands.commands.Menu.execute(Menu.java:37) ~[?:?]
        at vg.civcraft.mc.civmodcore.command.CommandHandler.execute(CommandHandler.java:26) ~[?:?]
        at vg.civcraft.mc.civmodcore.ACivMod.onCommand(ACivMod.java:64) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6cb0
]
        ... 15 more

**Comment by Maxopoly** [comment]
This was most likely caused by another exception during startup, which prevented other stuff from loading.

**Comment by ProgrammerDan** [comment]
Yeah, it's basically anytime a config specifies a recipe or factory but it doesn't actually exist. Looks like just all throughout needs better NPE captures with more informative outputs :)

**Comment by ProgrammerDan** [comment]
Fixed here https://github.com/Civcraft/FactoryMod/commit/40ccb708e4a6d8ff652393dd2636659fe5fb472f

Basically just testing more stuff for null, etc. Note there is a companion fix over in CivModCore for clickableinventory titles, bukkit has some limits we weren't respecting; now we are.

**Comment by Maxopoly** [comment]
Oh yeah the 32 character limit, I meant to put a limit in there, but forgot at some point. Very good and needed fixes overall, this should make working with this a lot easier for anyone who didn't write the code :D

**Comment by ProgrammerDan** [comment]
Hehe, my thoughts too. I'm sure there will be other little tweaks here or there. Lots of optimistic code to break :P
