### ISSUE TITLE
NPE PylonRecipe.getOutputRepresentation

### ISSUE THREAD

**Issue by erocs** [Civcraft/FactoryMod#275]
[Server thread/ERROR]: Could not pass event InventoryClickEvent to CivMenu v1.4.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
Caused by: java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.recipes.PylonRecipe.getOutputRepresentation(PylonRecipe.java:62) ~[?:?]
        at com.github.igotyou.FactoryMod.recipes.Upgraderecipe.getRecipeRepresentation(Upgraderecipe.java:46) ~[?:?]
        at com.github.igotyou.FactoryMod.utility.MenuBuilder.openRecipeBrowser(MenuBuilder.java:195) ~[?:?]
        at com.github.igotyou.FactoryMod.utility.MenuBuilder.access$200(MenuBuilder.java:41) ~[?:?]
        at com.github.igotyou.FactoryMod.utility.MenuBuilder$2.clicked(MenuBuilder.java:149) ~[?:?]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.itemClick(ClickableInventory.java:138) ~[?:?]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventoryListener.inventoryClick(ClickableInventoryListener.java:28) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]

**Comment by Maxopoly** [comment]
Pretty sure this was already fixed a while ago here https://github.com/Civcraft/FactoryMod/commit/66accf15873c94361aef09bc25c74e1fad9ddd71

I updated our staged version and will close this for now, if it reoccurs after tomorrow restart, just reopen the issue
