### ISSUE TITLE
Stack trace on Civtest

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#28]
2015-01-05 17:32:40 [WARN] [FactoryMod] Task #36 for FactoryMod v1.2.5 generated an exception
java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.utility.ItemList.amountAvailable(ItemList.java:219) ~[?:?]
        at com.github.igotyou.FactoryMod.utility.ItemList.allIn(ItemList.java:74) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.BaseFactory.isFuelAvailable(BaseFactory.java:428) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.NetherFactory.update(NetherFactory.java:153) ~[?:?]
        at com.github.igotyou.FactoryMod.managers.NetherFactoryManager$1.run(NetherFactoryManager.java:166) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]

**Comment by drjawa** [comment]
Should be fixed with https://github.com/Civcraft/FactoryMod/pull/29

**Comment by ttk2** [comment]
but that requires 3.0 right? that's not on Civtest yet
