### ISSUE TITLE
NPE in PercentageHealthRepair

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#299]
```
[09:09:36 WARN]: [FactoryMod] Task #7337842 for FactoryMod v2.2.17 generated an exception
java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.repairManager.PercentageHealthRepairManager$1.run(PercentageHealthRepairManager.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-047f737-744e1a1]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.10.2.jar:git-Spigot-047f737
-744e1a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-047f737-744e1a1]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-047f737-744e1a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-047f737-744e1a1]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-047f737-744e1a1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by ProgrammerDan** [comment]
May be a false flag since I'm apparently running a slightly older version.

**Comment by Maxopoly** [comment]
This was fixed with https://github.com/Civcraft/FactoryMod/commit/51143bebd9a1e8e38cc4135d398c1050eeff3243

**Comment by Maxopoly** [comment]
This one is a bit difficult (I have no idea why it's happening). Update to latest version and let me know if it's still happening.

**Comment by ProgrammerDan** [comment]
Will do. More likely then not it's just a follow-on failure from the other.
