### ISSUE TITLE
Concurrent mod exception

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#300]
```
[08:43:58 INFO]: [FactoryMod] Workshop at Location{world=CraftWorld{name=world},x=3606.0,y=96.0,z=2803.0,pitch=0.0,yaw=0.0} has been at no health for
too long and is being removed
[08:43:58 ERROR]: [FactoryMod] Fatal error while trying to save factory data
[08:43:58 WARN]: java.util.ConcurrentModificationException
[08:43:58 WARN]:        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[08:43:58 WARN]:        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
[08:43:58 WARN]:        at com.github.igotyou.FactoryMod.utility.FileHandler.save(FileHandler.java:71)
[08:43:58 WARN]:        at com.github.igotyou.FactoryMod.FactoryModManager.saveFactories(FactoryModManager.java:509)
[08:43:58 WARN]:        at com.github.igotyou.FactoryMod.ConfigParser$1.run(ConfigParser.java:125)
[08:43:58 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[08:43:58 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[08:43:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[08:43:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[08:43:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[08:43:58 WARN]: Exception in thread "Craft Scheduler Thread - 1445"
[08:43:58 WARN]: org.apache.commons.lang.UnhandledException: Plugin FactoryMod v2.2.17 generated an exception while executing task 71
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at com.github.igotyou.FactoryMod.utility.FactoryGarbageCollector.run(FactoryGarbageCollector.java:10)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by ProgrammerDan** [comment]
Note, this may be a false flag. Looks like I am running a slightly older version (2.2.17)

**Comment by Maxopoly** [comment]
This was fixed by https://github.com/Civcraft/FactoryMod/commit/51143bebd9a1e8e38cc4135d398c1050eeff3243
