### ISSUE TITLE
 Could not pass event PlayerInteractEvent to FactoryMod v1.3.4

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#40]
2015-02-02 21:09:02 [ERROR] Could not pass event PlayerInteractEvent to FactoryMod v1.3.4
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:103) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.Factorys.PrintingPress$PrintResult.hashCode(PrintingPress.java:623) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.PrintingPress.powerOn(PrintingPress.java:189) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.BaseFactory.togglePower(BaseFactory.java:166) ~[?:?]
        at com.github.igotyou.FactoryMod.listeners.FactoryModListener.playerInteractionEvent(FactoryModListener.java:205) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 15 more

**Comment by ttk2** [comment]
2015-02-02 21:09:03 [WARN] [FactoryMod] Task #37 for FactoryMod v1.3.4 generated an exception
java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.Factorys.PrintingPress$PrintResult.hashCode(PrintingPress.java:623) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.PrintingPress.fuelConsumed(PrintingPress.java:201) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.BaseFactory.update(BaseFactory.java:262) ~[?:?]
        at com.github.igotyou.FactoryMod.managers.PrintingPressManager$1.run(PrintingPressManager.java:185) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]


this occurred multiple times shortly after

**Comment by spaceFountain** [comment]
I can't really push a fix right now. I'm in class, but it seems we need to add a check before [this line](https://github.com/Civcraft/FactoryMod/blob/master/src/com/github/igotyou/FactoryMod/Factorys/PrintingPress.java#L540) calling [this function](http://jd.bukkit.org/rb/apidocs/org/bukkit/inventory/meta/BookMeta.html#hasTitle()) to make sure the book has a title. It's probably what's causing the first stack trace.

**Comment by spaceFountain** [comment]
The recurrence was probably someone just trying the same thing again.

**Comment by ttk2** [comment]
sounds good push when you can

**Comment by spaceFountain** [comment]
Hopefully [this](https://github.com/Civcraft/FactoryMod/pull/41) will fix the issue. Not really sure why it was coming up though.
