### ISSUE TITLE
divide by zero error on Civtest

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#50]
2015-02-21 22:07:24 [WARN] [FactoryMod] Task #35 for FactoryMod v1.3.4 generated an exception
java.lang.ArithmeticException: / by zero
        at com.github.igotyou.FactoryMod.Factorys.PrintingPress.printBooksUpdate(PrintingPress.java:269) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.PrintingPress.fuelConsumed(PrintingPress.java:210) ~[?:?]
        at com.github.igotyou.FactoryMod.Factorys.BaseFactory.update(BaseFactory.java:262) ~[?:?]
        at com.github.igotyou.FactoryMod.managers.PrintingPressManager$1.run(PrintingPressManager.java:185) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]

**Comment by WildWeazel** [comment]
This would have been what's now line 280, so pageCount was 0. It looks like that should be equal to the number of pages in the book being copied, so this is likely am example of #45

**Comment by ProgrammerDan** [comment]
Note: https://github.com/Civcraft/FactoryMod/issues/48

Solved as part of that other issue. I neglected to update here, but this is addressed now. I'm going to do one final testing pass to make sure I didn't miss it, but you shouldn't be seeing it on CivTest any longer.
