### ISSUE TITLE
Error on startup with repair factory. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#72]
2015-05-23 11:41:16 [ERROR] Error occurred while enabling FactoryMod v1.3.5 (Is it up to date?)
java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.FactoryModPlugin.getItems(FactoryModPlugin.java:381) ~[?:?]
        at com.github.igotyou.FactoryMod.properties.RepairFactoryProperties.fromConfig(RepairFactoryProperties.java:76) ~[?:?]
        at com.github.igotyou.FactoryMod.FactoryModPlugin.initConfig(FactoryModPlugin.java:320) ~[?:?]
        at com.github.igotyou.FactoryMod.FactoryModPlugin.onEnable(FactoryModPlugin.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by rourke750** [comment]
remove the comment tags here and below in the config: https://github.com/Civcraft/FactoryMod/blob/master/config.yml#L76

**Comment by rourke750** [comment]
Are you using the config on github?
