### ISSUE TITLE
Start up Null pointer after IO Refactor in the Compactor code path. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#96]
2015-06-13 10:00:54 [ERROR] Error occurred while enabling FactoryMod v1.4.0 (Is it up to date?)
java.lang.NullPointerException
        at com.github.igotyou.FactoryMod.properties.CompactorProperties.fromConfig(CompactorProperties.java:82) ~[?:?]
        at com.github.igotyou.FactoryMod.FactoryModPlugin.initConfig(FactoryModPlugin.java:412) ~[?:?]
        at com.github.igotyou.FactoryMod.FactoryModPlugin.onEnable(FactoryModPlugin.java:182) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by WildWeazel** [comment]
looks like the compactor construction config section is not properly structured? @TealNerd

**Comment by ProgrammerDan** [comment]
Oh, lmao. It's a config problem. He's got it written as:

compactor -> fuel -> costs -> etc.

Literally fuel is incorrectly listed as the only child of compactor, all other config items are children of "fuel". Easy fix, I'll do that directly.

**Comment by ProgrammerDan** [comment]
https://github.com/Civcraft/FactoryMod/pull/97 good to go

**Comment by ProgrammerDan** [comment]
@ttk2 probably in bad form but #97 is represented in #98, so if you want xp and this fixed and onto civtest in one go, #98 is your friend. Either way, #97 can be applied safely.

**Comment by TealNerd** [comment]
Lol oops I'm bad at yml

**Comment by ProgrammerDan** [comment]
I got your back, Teal.

**Comment by ttk2** [comment]
I assume 98 is mattas config? I wanted to get fixed repair cost capping
(nothing else) online by pushing this new version over with the live
config.

So it crashes without a compactor being specced? Could that be fixed real
quick or do you think we should just shove mattas config online at this
point?

WTF's is generally agreed to be more interesting. But mattas is def more
ready, changing later would be hard.

I'll leave the decision of which one we use to your judgement on how long
it's going to take and how feasible it is to get the stopgap anvil cost
limiter in place.

**Comment by ProgrammerDan** [comment]
@ttk2 Yeah, 98 is everything from matta (XP, XP Compactor, Armor, Weapon, and Tool Enchantment and Repair Factory balanced costs).

Stopgap anvil cost limiter was merged into main here: https://github.com/Civcraft/FactoryMod/pull/95

---- 

The issue was the compactor was specced, but the config had a construction error. I think this matches the level of tolerance for the other factories, but it's definitely something we could improve.

There's a big issue. Unless I'm reading it wrong, Teal's compactor is NOT compatible with Matta's compactor. They are two separate constructs, and never shall the twain meet. So the good news is there is no conflict, the bad news is we have two separate compactors.

------

As for judgment call, I'm not the big boss ;P . If you tell me exactly what you want out of this list, I'll pull it together as a separate pull request within 2 hours of your answer:

Items available:
* Repair Factory Cost Balance & fix to Plugin to load its config
* Tool, Weapon, and Armor enchantment Factories
* Nether Compactor / Decompactor
* XP Balance Changes (Matta's)

**Comment by ProgrammerDan** [comment]
@ttk2 you've seen the Repair factory pull, I just pushed to my repo, and can make a pull if you want it, just the Tools/Weapons/Armor factories and recipes, without any XP changes, and not changing repair

So if you want that to go out, just let me know and I'll make the pull request (won't make it now b/c there are already too many pending pulls).

**Comment by ttk2** [comment]
what do you mean just the tools/weaspons/armor factories? don't those require changes to XP?

**Comment by ProgrammerDan** [comment]
They do not. They require emerald blocks, not any produce unique to the xp
factories.

**Comment by ttk2** [comment]
hmm, does WTF have anything different for those? if not lets roll them, also see my other comment we need a quick fix to be able to load a config without a general compactor setup.

**Comment by ProgrammerDan** [comment]
Nope, nothing different. I'll need to update my branch against master, out
for dinner now but will issue updated pull tonight.

I'll look at the compactor question then too.

**Comment by ttk2** [comment]
if we can do that we can have repair and new equipment up after a day of testing, sounds good, keeping the general compactor from causing a crash out should be easy enough.

**Comment by WildWeazel** [comment]
This one is fixed, right?

**Comment by ttk2** [comment]
Seems to be.

**Comment by ProgrammerDan** [comment]
yeah compactor is still broken but this is fixed.
